Repository vic3-divergences/divergences, pull requests merged in 2023-03, with the labels that each got.

#180 fix objective localization
  localization/english/dvg_objectives_l_english.yml
Labels: bug

#182 5 Symbols
  gfx/coat_of_arms/colored_emblems/ce_celtic_knot.dds
  gfx/coat_of_arms/textured_emblems/te_austria_communist.dds
  gfx/coat_of_arms/textured_emblems/te_austria_monarchist.dds
  gfx/coat_of_arms/textured_emblems/te_eagle_shield_white_cross.dds
  gfx/coat_of_arms/textured_emblems/te_rhine.dds
Labels: Flags

#178 AI tweaks
  common/ai_strategies/02_diplomatic_strategies.txt
  common/ai_strategies/dvg_diplomatic_strategies.txt
  common/defines/dvg_defines.txt
  common/government_types/01_monarchies.txt
  common/history/ai/dvg_strategy.txt
  common/history/buildings/00_west_europe.txt
  common/history/buildings/01_south_europe.txt
  common/history/buildings/07_south_america.txt
  common/history/characters/0_dvg_burgundy.txt
  common/history/trade_routes/dvg_trade_routes.txt
  common/journal_entries/00_german_unification.txt
  common/modifiers/dvg_modifiers.txt
  events/german_unification.txt
  localization/english/dvg_ai_strategies_l_english.yml
  map_data/state_regions/07_south_america.txt
Labels: AI tweaks

#179 German AI Tweaks and flavor
  common/ai_strategies/00_default_strategy.txt
  common/ai_strategies/dvg_diplomatic_strategies.txt
  common/coat_of_arms/coat_of_arms/dvg_countries.txt
  common/country_creation/dvg_releasables_europe.txt
  common/country_definitions/dvg_europe.txt
  common/country_formation/dvg_formables_europe.txt
  common/dynamic_country_names/dvg_dynamic_country_names.txt
  common/flag_definitions/00_flag_definitions.txt
  common/flag_definitions/dvg_flag_definitions.txt
  common/government_types/001_dvg_monarchies.txt
  common/government_types/01_monarchies.txt
  common/government_types/04_theocracies.txt
  common/history/buildings/00_west_europe.txt
  common/history/characters/0_dvg_austria.txt
  common/history/characters/0_dvg_bavaria.txt
  common/history/countries/0_dvg_europe.txt
  common/history/diplomacy/00_customs_union.txt
  common/history/diplomacy/00_relations.txt
  common/history/diplomacy/00_rivalries.txt
  common/history/diplomacy/00_subject_relationships.txt
  common/history/pops/00_west_europe.txt
  common/history/population/0_dvg_europe.txt
  common/history/states/dvg_europe.txt
  common/ideologies/00_dvg_ig_ideologies.txt
  common/journal_entries/00_german_unification.txt
  common/journal_entries/dvg_danubian_unification.txt
  common/journal_entries/dvg_hre.txt
  common/journal_entries/dvg_rheinish_unification.txt
  common/journal_entries/dvg_saxony.txt
  common/modifiers/content_1_modifiers.txt
  common/on_actions/00_code_on_actions.txt
  events/german_unification.txt
  events/germany/dvg_danubian_unification.txt
  events/germany/dvg_elbian_confederation.txt
  events/germany/dvg_rheinish_unification.txt
  events/germany/dvg_saxony.txt
  localization/english/country_flavor_text_l_english.yml
  localization/english/dvg_countries_l_english.yml
  localization/english/dvg_flavor_bohemia_l_english.yml
  localization/english/dvg_flavor_danubian_l_english.yml
  localization/english/dvg_flavor_rheinish_l_english.yml
  localization/english/dvg_flavor_saxony_l_english.yml
  localization/english/dvg_government_l_english.yml
  localization/english/replace/countries_l_english.yml
  localization/english/replace/flavor_text_replaced_l_english.yml
Labels: AI tweaks, FLAVOR minor, Flags

#184 Generic diplomatic event to ask for help in war
  common/history/diplomacy/00_defensive_pacts.txt
  common/modifiers/dvg_modifiers.txt
  events/dvg_diplomatic_events.txt
  localization/english/dvg_diplomatic_events_l_english.yml
Labels: enhancement

#185 Germany tweaks
  common/coat_of_arms/coat_of_arms/dvg_countries.txt
  common/flag_definitions/dvg_flag_definitions.txt
  common/history/diplomacy/00_customs_union.txt
  gfx/coat_of_arms/colored_emblems/ce_bishop_crozier.dds
  gfx/coat_of_arms/colored_emblems/ce_osna.dds
Labels: Flags

#186 Improved Colonization Arcadia
  common/ai_strategies/00_default_strategy.txt
  common/ai_strategies/03_political_strategies.txt
  common/decisions/dvg_manifest_destiny.txt
  common/defines/dvg_defines.txt
  common/diplomatic_plays/00_diplomatic_plays.txt
  common/history/interests/dvg_interests.txt
  common/journal_entries/dvg_manifest_destiny.txt
  common/modifiers/content_1_modifiers.txt
  events/dvg_manifest_destiny.txt
  localization/english/dvg_flavor_manifest_destiny_l_english.yml
  localization/english/dvg_hub_names_l_english.yml
Labels: enhancement

#187 German Confederation when Germany is formed by BOH
  common/ai_strategies/00_default_strategy.txt
  common/coat_of_arms/coat_of_arms/dvg_countries.txt
  common/country_definitions/dvg_europe.txt
  common/country_formation/dvg_formables_europe.txt
  common/decisions/dvg_germany.txt
  common/dynamic_country_names/00_dynamic_country_names.txt
  common/flag_definitions/00_flag_definitions.txt
  common/journal_entries/00_german_unification.txt
  common/journal_entries/dvg_elbian_confederation.txt
  events/german_unification.txt
  events/germany/dvg_elbian_confederation.txt
  localization/english/dvg_countries_l_english.yml
  localization/english/dvg_flavor_bohemia_l_english.yml
Labels: FLAVOR minor
