Repository vic3-divergences/divergences, pull requests merged in 2023-05, with the labels that each got.

#217 Fix checks for every_subject_or_below
  events/dvg_dua.txt
  events/dvg_lotharingia.txt
  events/russia/dvg_nov_events.txt
Labels: bug

#218 Small Tweaks
  common/ai_strategies/02_diplomatic_strategies.txt
  common/ai_strategies/dvg_diplomatic_strategies.txt
  common/history/countries/0_dvg_europe.txt
  common/history/diplomacy/00_defensive_pacts.txt
  common/history/diplomacy/00_relations.txt
  common/history/population/0_dvg_central_asia.txt
  common/history/population/0_dvg_east_asia.txt
  common/history/population/0_dvg_europe.txt
  common/history/population/0_dvg_india.txt
  common/history/population/0_dvg_indonesia.txt
  common/history/population/0_dvg_middle_east.txt
  common/history/population/0_dvg_north_africa.txt
  common/history/population/0_dvg_oceania.txt
  common/history/population/0_dvg_siberia.txt
  common/history/population/0_dvg_subsaharan_africa.txt
  common/journal_entries/dvg_dua.txt
Labels: bug, AI tweaks

#221 Un-Hash out Guarani
  common/history/countries/0_dvg_ameriga.txt
Labels: bug

#222 Small Fixes
  common/ai_strategies/02_diplomatic_strategies.txt
  common/government_types/04_theocracies.txt
  common/on_actions/00_dvg_dua_code_on_actions.txt
Labels: bug

#223 Genoa Event Pictures, Minor Burma Update, and Minor Italian Flags
  common/coat_of_arms/coat_of_arms/dvg_countries.txt
  common/country_formation/dvg_formables_europe.txt
  common/dynamic_country_names/dvg_dynamic_country_names.txt
  common/flag_definitions/dvg_flag_definitions.txt
  common/history/buildings/01_south_europe.txt
  common/history/countries/0_dvg_east_asia.txt
  common/history/population/0_dvg_east_asia.txt
  common/history/states/dvg_east_asia.txt
  events/dvg_genoa.txt
  gfx/coat_of_arms/colored_emblems/ce_coa_lombardy.dds
  gfx/coat_of_arms/colored_emblems/ce_communist_anchor_hammer.dds
  gfx/coat_of_arms/colored_emblems/ce_genoa_eagle.dds
  gfx/coat_of_arms/textured_emblems/te_genoa_monarchy.dds
  gfx/coat_of_arms/textured_emblems/te_lombardia_coat.dds
  gfx/coat_of_arms/textured_emblems/te_seal_of_ambrosia.dds
  localization/english/country_flavor_text_l_english.yml
  localization/english/dvg_countries_l_english.yml
  map_data/state_regions/01_south_europe.txt
Labels: FLAVOR minor, Flags
