Repository vic3-divergences/divergences, pull requests merged in 2023-04, with the labels that each got.

#194 Fix infinite annexation offers
  common/decisions/dvg_zhourao.txt
  common/history/diplomacy/00_defensive_pacts.txt
  common/modifiers/dvg_modifiers.txt
  events/dvg_diplomatic_events.txt
  localization/english/dvg_diplomatic_events_l_english.yml
Labels: bug

#192 Fixes and Tweaks
  common/ai_strategies/00_default_strategy.txt
  common/ai_strategies/02_diplomatic_strategies.txt
  common/ai_strategies/dvg_diplomatic_strategies.txt
  common/cultures/00_cultures.txt
  common/cultures/dvg_cultures.txt
  common/history/buildings/00_west_europe.txt
  common/history/buildings/01_south_europe.txt
  common/history/buildings/11_east_asia.txt
  common/history/characters/0_dvg_aragon.txt
  common/history/characters/0_dvg_burgundy.txt
  common/history/characters/0_dvg_dual_monarchy.txt
  common/history/characters/0_dvg_japan.txt
  common/history/characters/0_dvg_spain.txt
  common/history/countries/0_dvg_europe.txt
  common/ideologies/00_leader_ideologies.txt
  common/journal_entries/dvg_nov_polarization.txt
Labels: bug, enhancement, AI tweaks

#199 AI Tweaks (Italy, South Germany, Russia, Novgorod)
  common/ai_strategies/00_default_strategy.txt
  common/ai_strategies/02_diplomatic_strategies.txt
  common/ai_strategies/dvg_diplomatic_strategies.txt
  common/country_formation/dvg_formables_europe.txt
  common/defines/dvg_defines.txt
  common/diplomatic_plays/00_diplomatic_plays.txt
  common/diplomatic_plays/dvg_diplomatic_plays.txt
  common/government_types/00_dvg_presidential_republic.txt
  common/history/characters/0_dvg_novgorod.txt
  common/history/characters/0_dvg_russia.txt
  common/history/states/dvg_east_asia.txt
  common/journal_entries/00_italian_unification.txt
  common/journal_entries/dvg_nov_polarization.txt
  common/journal_entries/dvg_poland_magnate_oligarchy.txt
  common/modifiers/00_static_modifiers.txt
  common/on_actions/00_code_on_actions.txt
  common/on_actions/00_dvg_russia_code_on_actions.txt
  events/german_unification.txt
  events/germany/dvg_rheinish_unification.txt
  events/russia/dvg_nov_events.txt
  localization/english/dvg_ai_strategies_l_english.yml
  localization/english/dvg_flavor_novgorod_l_english.yml
Labels: enhancement, AI tweaks

#159 Lotharingia and Atlantia flavor added
  common/ai_strategies/00_default_strategy.txt
  common/coat_of_arms/coat_of_arms/dvg_countries.txt
  common/country_creation/dvg_releasables_ameriga.txt
  common/country_definitions/dvg_ameriga.txt
  common/cultures/00_cultures.txt
  common/cultures/dvg_cultures.txt
  common/decisions/dvg_atlantia.txt
  common/decisions/dvg_lotharingia.txt
  common/diplomatic_plays/dvg_diplomatic_plays.txt
  common/dvg_lotharingia.txt
  common/dynamic_country_names/dvg_dynamic_country_names.txt
  common/flag_definitions/dvg_flag_definitions.txt
  common/government_types/00_dvg_special_dictatorship.txt
  common/history/buildings/07_south_america.txt
  common/history/characters/0_dvg_atlantia.txt
  common/history/characters/0_dvg_beornia.txt
  common/history/characters/0_dvg_lotharingia.txt
  common/history/countries/0_dvg_ameriga.txt
  common/history/diplomacy/00_rivalries.txt
  common/history/diplomacy/00_subject_relationships.txt
  common/history/diplomacy/00_truces.txt
  common/history/pops/07_south_america.txt
  common/history/states/dvg_ameriga.txt
  common/journal_entries/dvg_lotharingia.txt
  common/modifiers/dvg_lot_modifiers.txt
  common/scripted_triggers/00_clothes_triggers.txt
  events/dvg_atlantia.txt
  events/dvg_lotharingia.txt
  gfx/coat_of_arms/colored_emblems/ce_atlantian_rooster.dds
  gfx/coat_of_arms/colored_emblems/ce_cross_nea.dds
  gfx/coat_of_arms/colored_emblems/ce_dvg_torch.dds
  gfx/coat_of_arms/colored_emblems/ce_tricolor_bend_2.dds
  gfx/coat_of_arms/colored_emblems/te_atlantia_tricolonial.dds
  gfx/coat_of_arms/textured_emblems/te_atlantia_tricolonial.dds
  gfx/coat_of_arms/textured_emblems/te_golden_board.dds
  localization/english/country_flavor_text_l_english.yml
  localization/english/dvg_countries_l_english.yml
  localization/english/dvg_cultures_l_english.yml
  localization/english/dvg_diplomatic_plays_l_english.yml
  localization/english/dvg_flavor_atlantia_l_english.yml
  localization/english/dvg_flavor_lotharingia_l_english.yml
  localization/english/dvg_government_l_english.yml
  localization/english/dvg_hub_names_l_english.yml
  localization/english/dvg_interest_groups_l_english.yml
  localization/english/dvg_modifiers_l_english.yml
  localization/english/dvg_names_l_english.yml
  map_data/state_regions/07_south_america.txt
Labels: FLAVOR

#207 AI Tweaks and fixes
  common/ai_strategies/00_default_strategy.txt
  common/ai_strategies/02_diplomatic_strategies.txt
  common/ai_strategies/dvg_diplomatic_strategies.txt
  common/coat_of_arms/coat_of_arms/dvg_countries.txt
Labels: AI tweaks

#208 Update 05_north_america.txt
  map_data/state_regions/05_north_america.txt
Labels: enhancement

#193 Dual Monarchy - The Anglois Dilemma
  common/ai_strategies/00_default_strategy.txt
  common/ai_strategies/02_diplomatic_strategies.txt
  common/ai_strategies/dvg_diplomatic_strategies.txt
  common/coat_of_arms/coat_of_arms/dvg_countries.txt
  common/coat_of_arms/coat_of_arms/dvg_subs.txt
  common/country_definitions/dvg_europe.txt
  common/country_formation/dvg_formables_europe.txt
  common/decisions/dvg_france.txt
  common/diplomatic_plays/00_diplomatic_plays.txt
  common/diplomatic_plays/dvg_diplomatic_plays.txt
  common/dynamic_country_map_colors/dvg_default.txt
  common/dynamic_country_names/00_dynamic_country_names.txt
  common/dynamic_country_names/dvg_dynamic_country_names.txt
  common/flag_definitions/00_flag_definitions.txt
  common/flag_definitions/dvg_flag_definitions.txt
  common/history/ai/dvg_strategy.txt
  common/history/buildings/00_west_europe.txt
  common/history/countries/0_dvg_europe.txt
  common/ideologies/00_dvg_ig_ideologies.txt
  common/journal_entries/01_peoples_springtime_je.txt
  common/journal_entries/dvg_dua.txt
  common/journal_entries/dvg_france.txt
  common/journal_entries/dvg_reconquer_england.txt
  common/modifiers/DVG_POL_modifiers.txt
  common/modifiers/dvg_dua_modifiers.txt
  common/modifiers/dvg_modifiers.txt
  common/on_actions/00_code_on_actions.txt
  common/on_actions/00_dvg_dua_code_on_actions.txt
  common/parties/conservative_party.txt
  common/script_values/dvg_event_values.txt
  common/scripted_triggers/00_dvg_coa_triggers.txt
  events/dvg_diplomatic_events.txt
  events/dvg_dua.txt
  events/peoples_springtime.txt
  events/russia/dvg_green_prince.txt
  gfx/coat_of_arms/textured_emblems/te_dragon_eng.dds
  localization/english/dvg_ai_strategies_l_english.yml
  localization/english/dvg_countries_l_english.yml
  localization/english/dvg_diplomatic_plays_l_english.yml
  localization/english/dvg_flavor_dua_l_english.yml
  localization/english/dvg_flavor_england_l_english.yml
  localization/english/dvg_flavor_france_l_english.yml
  localization/english/dvg_flavor_spain_l_english.yml
  localization/english/dvg_flavor_zhourao_l_english.yml
  localization/english/dvg_modifiers_l_english.yml
Labels: FLAVOR, Flags

#202 Tatar rework
  common/ai_strategies/00_default_strategy.txt
  common/ai_strategies/dvg_diplomatic_strategies.txt
  common/coat_of_arms/coat_of_arms/dvg_countries.txt
  common/country_creation/dvg_releasables_central_asia.txt
  common/country_definitions/dvg_central_asia.txt
  common/country_definitions/dvg_europe.txt
  common/country_definitions/dvg_middle_east.txt
  common/country_definitions/dvg_siberia.txt
  common/country_formation/dvg_formables_europe.txt
  common/cultures/00_cultures.txt
  common/cultures/dvg_cultures.txt
  common/diplomatic_plays/dvg_diplomatic_plays.txt
  common/discrimination_traits/dvg_cultural_descriptive.txt
  common/flag_definitions/dvg_flag_definitions.txt
  common/history/characters/0_dvg_crimea.txt
  common/history/countries/0_dvg_central_asia.txt
  common/history/pops/01_south_europe.txt
  common/history/pops/02_east_europe.txt
  common/history/pops/08_middle_east.txt
  common/history/pops/09_central_asia.txt
  common/history/pops/14_siberia.txt
  common/history/states/dvg_central_asia.txt
  common/history/states/dvg_europe.txt
  common/history/states/dvg_siberia.txt
  events/dvg_dzungaria.txt
  events/dvg_kipchak.txt
  localization/english/country_flavor_text_l_english.yml
  localization/english/dvg_countries_l_english.yml
  localization/english/dvg_cultures_l_english.yml
  localization/english/dvg_diplomatic_plays_l_english.yml
  localization/english/dvg_flavor_poland_l_english.yml
  localization/english/dvg_flavor_russia_l_english.yml
  localization/english/dvg_hub_names_l_english.yml
  localization/english/dvg_names_l_english.yml
  localization/english/replace/hub_names_replaced_l_english.yml
  localization/english/replace/modifiers_l_english.yml
Labels: FLAVOR minor, Flags

#209 ATH Remove some buildings
  common/history/buildings/05_north_america.txt
Labels: enhancement

#214 Dual Monarchy fixes
  events/dvg_diplomatic_events.txt
  events/dvg_dua.txt
  localization/english/dvg_flavor_dua_l_english.yml
Labels: bug
